/* THIS FILE IS AUTOGENERATED FROM AppNotificationServiceOptions.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_AppNotificationServiceOptionsBinding_h
#define mozilla_dom_AppNotificationServiceOptionsBinding_h

#include "NotificationBinding.h"
#include "js/RootingAPI.h"
#include "jspubtd.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/Nullable.h"

namespace mozilla {
namespace dom {

struct AppNotificationServiceOptionsAtoms;
struct NativePropertyHooks;
struct NotificationBehavior;
class ProtoAndIfaceCache;

} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {

struct AppNotificationServiceOptions : public DictionaryBase
{
  nsString mData;
  nsString mDbId;
  nsString mDir;
  nsString mId;
  nsString mLang;
  nsString mManifestURL;
  NotificationBehavior mMozbehavior;
  nsString mTag;
  bool mTextClickable;

  AppNotificationServiceOptions();

  explicit inline AppNotificationServiceOptions(const FastDictionaryInitializer& )
    : mMozbehavior(FastDictionaryInitializer())
  {
    // Do nothing here; this is used by our "Fast" subclass
  }

  explicit inline AppNotificationServiceOptions(const AppNotificationServiceOptions& aOther)
    : mMozbehavior(FastDictionaryInitializer())
  {
    *this = aOther;
  }

  bool
  Init(JSContext* cx, JS::Handle<JS::Value> val, const char* sourceDescription = "Value", bool passedToJSImpl = false);

  bool
  Init(const nsAString& aJSON);

  bool
  ToObjectInternal(JSContext* cx, JS::MutableHandle<JS::Value> rval) const;

  bool
  ToJSON(nsAString& aJSON) const;

  void
  TraceDictionary(JSTracer* trc);

  void
  operator=(const AppNotificationServiceOptions& aOther);

private:
  static bool
  InitIds(JSContext* cx, AppNotificationServiceOptionsAtoms* atomsCache);
};

namespace binding_detail {
struct FastAppNotificationServiceOptions : public AppNotificationServiceOptions
{
  inline FastAppNotificationServiceOptions()
    : AppNotificationServiceOptions(FastDictionaryInitializer())
  {
    // Doesn't matter what int we pass to the parent constructor
  }
};
} // namespace binding_detail


} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_AppNotificationServiceOptionsBinding_h
