/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim:set ts=2 sw=2 sts=2 et cindent: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/* THIS FILE IS AUTOGENERATED FROM AutocompleteErrorEvent.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_AutocompleteErrorEvent_h
#define mozilla_dom_AutocompleteErrorEvent_h

#include "AutocompleteErrorEventBinding.h"
#include "mozilla/Attributes.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/AutocompleteErrorEventBinding.h"
#include "mozilla/dom/BindingUtils.h"
#include "mozilla/dom/Event.h"

struct JSContext;
namespace mozilla {
namespace dom {

class AutocompleteErrorEvent : public Event
{
public:
  NS_DECL_ISUPPORTS_INHERITED
  NS_DECL_CYCLE_COLLECTION_SCRIPT_HOLDER_CLASS_INHERITED(AutocompleteErrorEvent, Event)
protected:
  virtual ~AutocompleteErrorEvent();
  explicit AutocompleteErrorEvent(mozilla::dom::EventTarget* aOwner);

  AutoCompleteErrorReason mReason;

public:
  virtual AutocompleteErrorEvent* AsAutocompleteErrorEvent() override;

  virtual JSObject* WrapObjectInternal(JSContext* aCx, JS::Handle<JSObject*> aGivenProto) override;

  static already_AddRefed<AutocompleteErrorEvent> Constructor(mozilla::dom::EventTarget* aOwner, const nsAString& aType, const AutocompleteErrorEventInit& aEventInitDict);

  static already_AddRefed<AutocompleteErrorEvent> Constructor(const GlobalObject& aGlobal, const nsAString& aType, const AutocompleteErrorEventInit& aEventInitDict, ErrorResult& aRv);

  AutoCompleteErrorReason Reason() const;
};

} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_AutocompleteErrorEvent_h
