/* THIS FILE IS AUTOGENERATED FROM ChildNode.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_ChildNodeBinding_h
#define mozilla_dom_ChildNodeBinding_h

#include "js/RootingAPI.h"
#include "jspubtd.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/Nullable.h"

namespace mozilla {
namespace dom {

struct NativePropertyHooks;
class ProtoAndIfaceCache;

} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {



} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_ChildNodeBinding_h
