/* THIS FILE IS AUTOGENERATED FROM FileMode.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_FileModeBinding_h
#define mozilla_dom_FileModeBinding_h

#include "js/RootingAPI.h"
#include "jspubtd.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/Nullable.h"

namespace mozilla {
namespace dom {

struct NativePropertyHooks;
class ProtoAndIfaceCache;

} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {

enum class FileMode : uint32_t {
  Readonly,
  Readwrite,
  EndGuard_
};

namespace FileModeValues {
extern const EnumEntry strings[3];
} // namespace FileModeValues

bool
ToJSValue(JSContext* aCx, FileMode aArgument, JS::MutableHandle<JS::Value> aValue);


} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_FileModeBinding_h
