/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim:set ts=2 sw=2 sts=2 et cindent: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/* THIS FILE IS AUTOGENERATED FROM FontFaceSetLoadEvent.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_FontFaceSetLoadEvent_h
#define mozilla_dom_FontFaceSetLoadEvent_h

#include "mozilla/Attributes.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingUtils.h"
#include "mozilla/dom/Event.h"
#include "mozilla/dom/FontFaceSetLoadEventBinding.h"

struct JSContext;
namespace mozilla {
namespace dom {

class FontFaceSetLoadEvent : public Event
{
public:
  NS_DECL_ISUPPORTS_INHERITED
  NS_DECL_CYCLE_COLLECTION_SCRIPT_HOLDER_CLASS_INHERITED(FontFaceSetLoadEvent, Event)
protected:
  virtual ~FontFaceSetLoadEvent();
  explicit FontFaceSetLoadEvent(mozilla::dom::EventTarget* aOwner);

  nsTArray<RefPtr<FontFace>> mFontfaces;

public:
  virtual FontFaceSetLoadEvent* AsFontFaceSetLoadEvent() override;

  virtual JSObject* WrapObjectInternal(JSContext* aCx, JS::Handle<JSObject*> aGivenProto) override;

  static already_AddRefed<FontFaceSetLoadEvent> Constructor(mozilla::dom::EventTarget* aOwner, const nsAString& aType, const FontFaceSetLoadEventInit& aEventInitDict);

  static already_AddRefed<FontFaceSetLoadEvent> Constructor(const GlobalObject& aGlobal, const nsAString& aType, const FontFaceSetLoadEventInit& aEventInitDict, ErrorResult& aRv);

  void GetFontfaces(nsTArray<RefPtr<FontFace>>& aRetVal) const;
};

} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_FontFaceSetLoadEvent_h
