/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim:set ts=2 sw=2 sts=2 et cindent: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/* THIS FILE IS AUTOGENERATED FROM GamepadEvent.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_GamepadEvent_h
#define mozilla_dom_GamepadEvent_h

#include "mozilla/Attributes.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingUtils.h"
#include "mozilla/dom/Event.h"
#include "mozilla/dom/GamepadEventBinding.h"

struct JSContext;
namespace mozilla {
namespace dom {

class GamepadEvent : public Event
{
public:
  NS_DECL_ISUPPORTS_INHERITED
  NS_DECL_CYCLE_COLLECTION_SCRIPT_HOLDER_CLASS_INHERITED(GamepadEvent, Event)
protected:
  virtual ~GamepadEvent();
  explicit GamepadEvent(mozilla::dom::EventTarget* aOwner);

  RefPtr<Gamepad> mGamepad;

public:
  virtual GamepadEvent* AsGamepadEvent() override;

  virtual JSObject* WrapObjectInternal(JSContext* aCx, JS::Handle<JSObject*> aGivenProto) override;

  static already_AddRefed<GamepadEvent> Constructor(mozilla::dom::EventTarget* aOwner, const nsAString& aType, const GamepadEventInit& aEventInitDict);

  static already_AddRefed<GamepadEvent> Constructor(const GlobalObject& aGlobal, const nsAString& aType, const GamepadEventInit& aEventInitDict, ErrorResult& aRv);

  Gamepad* GetGamepad() const;
};

} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_GamepadEvent_h
